
// PRODUCT TYPES

export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const FETCHED_PRODUCT = "FETCHED_PRODUCT"
export const FETCHED_MORE_PRODUCT = "FETCHED_MORE_PRODUCT"


// CART TYPES

export const ADD_TO_CART = "ADD_TO_CART"
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
export const OPEN_CART = "OPEN_CART"
export const CLOSE_CART = "CLOSE_CART"
export const CLEAR_CART = "CLEAR_CART"



export const INIT_LOCALSTORAGE = "INIT_LOCALSTORAGE"